[package]
name = "xenia"
version = "0.0.1"
edition = "2021"
description = "xenia"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
bitflags = "2.5.0"
linux-raw-sys = { version = "0.6.4", default-features = false, features = ["errno", "general", "system", "no_std"] }
