[package]
name = "xenia"
version = "0.0.2"
edition = "2021"
description = "xenia"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
bitflags = "2.9.1"
linux-raw-sys = { version = "0.10.0", default-features = false, features = [
    "errno",
    "general",
    "system",
    "no_std",
] }
